name: Create infrastructure on Magalu Cloud
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0  # Ajuste para a versão do Terraform que você usa

    - name: Install mgcli
      run: |
          mkdir -p ~/mgc_cli
          wget https://github.com/MagaluCloud/mgccli/releases/download/v0.23.0/mgccli_0.23.0_linux_amd64.tar.gz
          tar -xvf mgccli_0.23.0_linux_amd64.tar.gz -C ~/mgc_cli
          echo "MGCLI_PATH=$HOME/mgc_cli" >> $GITHUB_ENV
          echo "$HOME/mgc_cli" >> $GITHUB_PATH

    - name: Export PATH
      run: echo "PATH=$HOME/mgc_cli:$PATH" >> $GITHUB_ENV

    - name: Set Terraform Environment Variables
      run: echo "TF_VAR_mgc_api_key=${{ secrets.MGC_API_KEY }}" >> $GITHUB_ENV
    - name: Set Terraform Environment Variables
      run: echo "TF_VAR_mgc_obj_key_id=${{ secrets.MGC_OBJ_KEY_ID }}" >> $GITHUB_ENV
    - name: Set Terraform Environment Variables
      run: echo "TF_VAR_mgc_obj_key_secret=${{ secrets.MGC_OBJ_KEY_SECRET }}" >> $GITHUB_ENV
    - name: Set Terraform Environment Variables
      run: echo "TF_VAR_mgc_region=${{ secrets.MGC_REGION }}" >> $GITHUB_ENV

#    - name: Terraform Init
#      run: terraform init

#    - name: Terraform Plan
#      id: plan
#      run: terraform plan -out=tfplan

#    - name: Terraform Apply
#      if: github.event_name == 'push'
#      run: terraform apply -auto-approve tfplan

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch'
      run: terraform apply -auto-approve tfplan