name: Generate Graph
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Terramaid
      run: | 
        wget https://github.com/RoseSecurity/Terramaid/releases/download/v1.6.3/Terramaid_Linux_x86_64.tar.gz
        tar -xzvf /tmp/Terramaid_Linux_x86_64.tar.gz -C /tmp
        mv -v /tmp/Terramaid /usr/local/bin/terramaid
        chmod +x /usr/local/bin/terramaid

        - name: Init
          run: terraform init --upgrade
        
        - name: Plan
          run: terraform plan -out=plan.out

        - name: Terramaid
          run: terramaid 

