name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.3  # Especifica a versão do Terraform

#    - name: Install Graphviz
#      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Terraform Init
      run: terraform init --upgrade

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Test
      run: terraform test  # Certifique-se de que o comando 'terraform test' está disponível no seu contexto

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Graph
      run: terraform graph | tee graph.dot | dot -Tpng > graph.png

    - name: Upload Terraform Graph
      uses: actions/upload-artifact@v3
      with:
        name: terraform-graph
        path: graph.png